config/routes.rb
Rails.application.routes.draw do
  resources :compras
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/compra.rb
class Compra < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/compras_controller.rb
class ComprasController < ApplicationController
  before_action :set_compra, only: [:show, :edit, :update, :destroy]

  # GET /compras
  # GET /compras.json
  def index
    @compras = Compra.all
  end

  # GET /compras/1
  # GET /compras/1.json
  def show
  end

  # GET /compras/new
  def new
    @compra = Compra.new
  end

  # GET /compras/1/edit
  def edit
  end

  # POST /compras
  # POST /compras.json
  def create
    @compra = Compra.new(compra_params)

    respond_to do |format|
      if @compra.save
        format.html { redirect_to @compra, notice: 'Compra was successfully created.' }
        format.json { render :show, status: :created, location: @compra }
      else
        format.html { render :new }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compras/1
  # PATCH/PUT /compras/1.json
  def update
    respond_to do |format|
      if @compra.update(compra_params)
        format.html { redirect_to @compra, notice: 'Compra was successfully updated.' }
        format.json { render :show, status: :ok, location: @compra }
      else
        format.html { render :edit }
        format.json { render json: @compra.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compras/1
  # DELETE /compras/1.json
  def destroy
    @compra.destroy
    respond_to do |format|
      format.html { redirect_to compras_url, notice: 'Compra was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compra
      @compra = Compra.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compra_params
      params.require(:compra).permit(:idade, :sexo, :estado_civil, :cidade, :bairro, :estado, :produto, :preco, :estabelecimento)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/compras_helper.rb
module ComprasHelper
end

app/views/compras/_form.html.erb
<%= form_with(model: compra, local: true) do |form| %>
  <% if compra.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(compra.errors.count, "error") %> prohibited this compra from being saved:</h2>

      <ul>
      <% compra.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :idade %>
    <%= form.number_field :idade, id: :compra_idade %>
  </div>

  <div class="field">
    <%= form.label :sexo %>
    <%= form.text_field :sexo, id: :compra_sexo %>
  </div>

  <div class="field">
    <%= form.label :estado_civil %>
    <%= form.text_field :estado_civil, id: :compra_estado_civil %>
  </div>

  <div class="field">
    <%= form.label :cidade %>
    <%= form.text_field :cidade, id: :compra_cidade %>
  </div>

  <div class="field">
    <%= form.label :bairro %>
    <%= form.text_field :bairro, id: :compra_bairro %>
  </div>

  <div class="field">
    <%= form.label :estado %>
    <%= form.text_field :estado, id: :compra_estado %>
  </div>

  <div class="field">
    <%= form.label :produto %>
    <%= form.text_field :produto, id: :compra_produto %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco, id: :compra_preco %>
  </div>

  <div class="field">
    <%= form.label :estabelecimento %>
    <%= form.text_field :estabelecimento, id: :compra_estabelecimento %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/compras/edit.html.erb
<h1>Editing Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Show', @compra %> |
<%= link_to 'Back', compras_path %>

app/views/compras/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Compras</h1>

<table>
  <thead>
    <tr>
      <th>Idade</th>
      <th>Sexo</th>
      <th>Estado civil</th>
      <th>Cidade</th>
      <th>Bairro</th>
      <th>Estado</th>
      <th>Produto</th>
      <th>Preco</th>
      <th>Estabelecimento</th>
      <th>Data da Compra</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @compras.each do |compra| %>
      <tr>
        <td><%= compra.idade %></td>
        <td><%= compra.sexo %></td>
        <td><%= compra.estado_civil %></td>
        <td><%= compra.cidade %></td>
        <td><%= compra.bairro %></td>
        <td><%= compra.estado %></td>
        <td><%= compra.produto %></td>
        <td><%= compra.preco %></td>
        <td><%= compra.estabelecimento %></td>
        <td><%= compra.data_compra.to_time.strftime('%d/%m/%Y') %></td>
        <td><%= link_to 'Show', compra %></td>
        <td><%= link_to 'Edit', edit_compra_path(compra) %></td>
        <td><%= link_to 'Destroy', compra, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Compra', new_compra_path %>

app/views/compras/new.html.erb
<h1>New Compra</h1>

<%= render 'form', compra: @compra %>

<%= link_to 'Back', compras_path %>

app/views/compras/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idade:</strong>
  <%= @compra.idade %>
</p>

<p>
  <strong>Sexo:</strong>
  <%= @compra.sexo %>
</p>

<p>
  <strong>Estado civil:</strong>
  <%= @compra.estado_civil %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @compra.cidade %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @compra.bairro %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @compra.estado %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @compra.produto %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @compra.preco %>
</p>

<p>
  <strong>Estabelecimento:</strong>
  <%= @compra.estabelecimento %>
</p>

<%= link_to 'Edit', edit_compra_path(@compra) %> |
<%= link_to 'Back', compras_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GeradorDados</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>